### ISSUE TITLE
issue with mvn package

### ISSUE THREAD

**Issue by jayashree12** [cloudfoundry-community/s3-cf-service-broker#12]
Hello,
I installed the package from github and wanted to build the package using mvn.but i revcieved the below error with the pom.xml file:

[INFO] Scanning for projects...
Downloading: http://repo.spring.io/libs-snapshot/org/springframework/boot/spring-boot-starter-parent/1.1.4.RELEASE/spring-boot-starter-parent-1.1.4.RELEASE.pom
Downloading: https://repo.maven.apache.org/maven2/org/springframework/boot/spring-boot-starter-parent/1.1.4.RELEASE/spring-boot-starter-parent-1.1.4.RELEASE.pom
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for org.cloudfoundry.broker:s3-cf-service-broker:2.3.0-SNAPSHOT: Could not transfer artifact org.springframework.boot:spring-boot-starter-parent:pom:1.1.4.RELEASE from/to spring-io (http://repo.spring.io/libs-snapshot): repo.spring.io: unknown error and 'parent.relativePath' points at wrong local POM @ line 4, column 10
 @
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
[ERROR]   The project org.cloudfoundry.broker:s3-cf-service-broker:2.3.0-SNAPSHOT (/home/js37gfy/s3-cf-service-broker/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for org.cloudfoundry.broker:s3-cf-service-broker:2.3.0-SNAPSHOT: Could not transfer artifact org.springframework.boot:spring-boot-starter-parent:pom:1.1.4.RELEASE from/to spring-io (http://repo.spring.io/libs-snapshot): repo.spring.io: unknown error and 'parent.relativePath' points at wrong local POM @ line 4, column 10: Unknown host repo.spring.io: unknown error -> [Help 2]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException
bash-4.1$

clould you please help sort out this.

**Comment by davidehringer** [comment]
@jayashree12  I've been unable to reproduce your error.  Are you still seeing this issue?

**Comment by drnic** [comment]
I didn't experience this - rather I had to setup my AWS env vars before `mvn package` would build successfully. I added a commit to allow `.envrc` file.

(Sorry for committing directly to master)

**Comment by bodymindarts** [comment]
If you simply want to package to create a `.jar` without running the tests. you can also run `mvn package -DskipTests`. That way it doesn't matter if you have aws creds set or not.

**Comment by drnic** [comment]
Thanks!
