### ISSUE TITLE
What commit is safe to use?

### ISSUE THREAD

**Issue by simonjohansson** [cloudfoundry-community/s3-cf-service-broker#13]
Releases or at least tagging for safe commits would be lovely :)

**Comment by davidehringer** [comment]
@simonjohansson I'll get some tags created and release notes to address this.

**Comment by simonjohansson** [comment]
@davidehringer lovely, thanks!

**Comment by davidehringer** [comment]
@simonjohansson  I've tagged known stable versions and noted so in the README.  

I personally haven't yet vetted fully some of the most recent changes in master so they aren't yet part of a tag.

**Comment by simonjohansson** [comment]
@davidehringer danke!
